data:
    image: debian
    container_name: data-symfony
    working_dir: /var
    volumes:
        - /var/lib/mysql
        - /var/log/nginx
    tty: yes

db:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
    volumes_from:
        - data

php:
    build: ./docker/php
    container_name: symfony
    links:
        - db
    ports:
        - 9000:9000
    working_dir: /var/www/html
    volumes:
        - ./app:/var/www/html
    volumes_from:
        - data

nginx:
    image: nginx
    container_name: nginx
    links:
        - php
    ports:
        - 80:80
        - 443:443
    working_dir: /var/www/html
    volumes:
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
    volumes_from:
        - php
        - data

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - db
    ports:
        - 8080:8080