php-symfony:
  build: ./docker/php-symfony
  container_name: symfony
  links:
      - mysql
  ports:
      - "80:80"
  volumes:
      - ./app:/var/www/html
#  volumes_from:
#      - data:rw

nginx:
    build: ./docker/nginx
    container_name: nginx
    links:
        - php-symfony
    ports:
      - "8080:80"

mysql:
    build: ./docker/mysql
    command: mysqld --port 3306
    container_name: mysql
    environment:
        MYSQL_USER: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: symfony

#data:
#    build: ./docker/data
#    container_name: data
#    volumes:
#         - ./app:/app