php-apache:
    image: php:7-apache
    container_name: php-apache
    links:
        - db
    ports:
        - 80:80
    working_dir: /var/www/html/
    volumes:
        - ./app:/var/www/html
    volumes_from:
        - data
    tty: true

php-fpm:
    build: ./docker/php
    container_name: php-fpm
    links:
        - db
    ports:
        - 9000:9000
        - 8448:8448
        - 8000:8000
    working_dir: /var/www/html/
    volumes:
        - ./app:/var/www/html
    volumes_from:
        - data
    tty: true
    env_file:
        - ./docker.env
    entrypoint: /entrypoint.sh


nginx:
    image: nginx
    container_name: nginx
    links:
        - php-fpm
    ports:
        - 8888:80
        - 443:443
    working_dir: /var/www/html
    volumes:
        - ./docker/nginx/conf.d:/etc/nginx/conf.d
    volumes_from:
        - php-fpm
        - data

db:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
    volumes_from:
        - data

data:
    image: debian
    container_name: data
    working_dir: /var
    volumes:
        - /var/lib/mysql
        - /var/log/nginx
    tty: yes

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - db
    ports:
        - 8080:80

gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    volumes_from:
        - data
    ports:
        - 3000:8080
        #- 443:443
        #- 22:22
