db:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: root
#        MYSQL_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: symfony

php:
    build: ./docker/php
    container_name: symfony
    links:
        - db
    ports:
        - 9000:9000
    working_dir: /var/www/html
    volumes:
        - ./app:/var/www/html

nginx:
    build: ./docker/nginx
    container_name: nginx
    links:
        - php
    ports:
        - 80:80
        - 443:443
    working_dir: /www
    volumes:
        - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    volumes_from:
        - php

