data:
    image: debian
    container_name: data-symfony
    volumes:
        - /var/lib/mysql

db:
    image: mysql
    container_name: mysql
    ports:
        - 3306:3306
    environment:
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
    volumes_from:
        - data

php:
    build: ./docker/php
    container_name: symfony
    links:
        - db
    ports:
        - 80:80
    working_dir: /var/www/html
    volumes:
        - ./app:/var/www/html

#nginx:
#    build: ./docker/nginx
#    container_name: nginx
#    links:
#        - php
#    ports:
#        - 80:80
#        - 443:443
#    working_dir: /var/www/html
#    volumes_from:
#        - php

phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
        - db
    ports:
     - 8080:8080

