version: '3'

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile-php
        container_name: php-fpm-${PROJECT_NAME}
        ports:
            - 8000
        working_dir: /var/www/html/
        volumes:
            - ../app:/var/www/html
        tty: true
        env_file:
            - ./.env
        entrypoint: /entrypoint.sh
        networks:
          - traefik
        labels:
            - "traefik.docker.network=traefik"
            - "traefik.backend=api"
            - "traefik.port=80"

    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        container_name: nginx-${PROJECT_NAME}
        links:
            - php-fpm
            - node
        ports:
            - 80
            - 443
        working_dir: /var/www/html
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ../app:/var/www/html
            - data-volume:/etc/letsencrypt
            - data-volume:/var/log/nginx

    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        container_name: node-${PROJECT_NAME}
        ports:
            - 4200
        tty: true
        working_dir: /var/www/html
        volumes:
            - ../app:/var/www/html
        env_file:
        - ./.env
        entrypoint: /entrypoint.sh

    db:
        image: mysql:8.0.13
        container_name: db-${PROJECT_NAME}
        ports:
            - 3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${PROJECT_NAME}
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        volumes:
            - data-volume:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin-${PROJECT_NAME}
        ports:
            - 80

    portainer:
        image: portainer/portainer
        container_name: portainer-${PROJECT_NAME}
        command: -H unix:///var/run/docker.sock
        ports:
            - 9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    traefik:
        image: traefik:1.7.4
        container_name: traefik-${PROJECT_NAME}
        ports:
            - ${TRAEFIK_PORT}:80
            - ${TRAEFIK_PORT_HTTPS}:443
            - ${TRAEFIK_DASHBOARD_PORT}:8080
        volumes:
            - ./traefik/traefik.toml:/etc/traefik/traefik.toml
        networks:
          - webgateway

networks:
    webgateway:
        driver: bridge
    traefik:
        external:
            name: traefik_webgateway

volumes:
    data-volume: {}
    portainer_data: {}
