version: '3'

services:
    php-fpm:
        build: ./php
        container_name: php-fpm-${PROJECT_NAME}
        links:
            - db
        ports:
            - ${APP_DEV_PORT}:8000
        working_dir: /var/www/html/
        volumes:
            - ../app:/var/www/html
        tty: true
        env_file:
            - ./.env
        entrypoint: /entrypoint.sh

    nginx:
        build: ./nginx
        container_name: nginx-${PROJECT_NAME}
        links:
            - php-fpm
            - node
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        working_dir: /var/www/html
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ../app:/var/www/html
            - data:/etc/letsencrypt
            - data:/var/log/nginx

    db:
        build: ./db
        container_name: db-${PROJECT_NAME}
        ports:
            - ${DATABASE_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${PROJECT_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./db/db-persist:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin-${PROJECT_NAME}
        links:
            - db
        ports:
            - ${PHPMYADMIN_PORT}:80

    node:
        build:
            context: ./node
            dockerfile: ./Dockerfile
        container_name: node-${PROJECT_NAME}
        ports:
            - ${ANGULAR_PORT}:4200
        tty: true
        working_dir: /var/www/html
        volumes:
            - ../app:/var/www/html

volumes:
    data: {}
