version: '2'
services:
    php-fpm:
        build: ./php
        container_name: php-fpm-melody
        links:
            - db
        ports:
            - 8000:8000
        working_dir: /var/www/html/
        volumes:
            - ../app:/var/www/html
        tty: true
        env_file:
            - ./docker.env
        entrypoint: /entrypoint.sh

    nginx:
        image: nginx:latest
        container_name: nginx-melody
        links:
            - php-fpm
        ports:
            - 80:80
            - 443:443
        working_dir: /var/www/html
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d

    db:
        image: mysql:8
        container_name: db-melody
        ports:
            - 3306:3306
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root

    data:
        image: debian:jessie
        container_name: data-melody
        working_dir: /var
        volumes:
            - /var/lib/mysql
            - /var/log/nginx
        tty: yes

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin-melody
        links:
            - db
        ports:
            - 8080:80
