version: '3'

services:
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile-php
        container_name: php-fpm-${PROJECT_NAME}
        ports:
            - ${APP_DEV_PORT}:8000
        working_dir: /var/www/html/
        volumes:
            - ../app:/var/www/html
        tty: true
        env_file:
            - ./.env
        entrypoint: /entrypoint.sh

    nginx:
        build:
            context: .
            dockerfile: Dockerfile-nginx
        container_name: nginx-${PROJECT_NAME}
        links:
            - php-fpm
            - node
        ports:
            - ${NGINX_PORT}:80
            - ${NGINX_HTTPS_PORT}:443
        working_dir: /var/www/html
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ../app:/var/www/html
            - data-volume:/etc/letsencrypt
            - data-volume:/var/log/nginx

    node:
        build:
            context: .
            dockerfile: Dockerfile-node
        container_name: node-${PROJECT_NAME}
        ports:
            - ${ANGULAR_PORT}:4200
        tty: true
        working_dir: /var/www/html
        volumes:
            - ../app:/var/www/html
        env_file:
        - ./.env
        entrypoint: /entrypoint.sh
    
    db:
        image: mysql:8.0.13
        container_name: db-${PROJECT_NAME}
        ports:
            - ${DATABASE_PORT}:3306
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${PROJECT_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - data-volume:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin-${PROJECT_NAME}
        ports:
            - ${PHPMYADMIN_PORT}:80

    portainer:
        image: portainer/portainer
        container_name: portainer-${PROJECT_NAME}
        command: -H unix:///var/run/docker.sock
        ports:
            - ${PORTAINER_PORT}:9000
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data

    rancher:
        image: rancher/rancher
        container_name: rancher-${PROJECT_NAME}
        ports:
            - ${RANCHER_PORT}:443

    traefik:
        image: traefik:1.7.4
        container_name: traefik-${PROJECT_NAME}
        ports:
            - ${TRAEFIK_PORT}:80
            - ${TRAEFIK_DASHBOARD_PORT}:8080
        volumes:
            - ./traefik/traefik.toml:/etc/traefik/traefik.toml

volumes:
    data-volume: {}
    portainer_data: {}
