version: '3'

services:
    php-fpm:
        build: ./php
        container_name: php-fpm-${PROJECT_NAME}
        links:
            - db
        ports:
            - 8000:8000
        working_dir: /var/www/html/
        volumes:
            - ../app:/var/www/html
        tty: true
        env_file:
            - ./.env
        entrypoint: /entrypoint.sh

    nginx:
        build: ./nginx
        container_name: nginx-${PROJECT_NAME}
        links:
            - php-fpm
            - node
        ports:
            - 80:80
            - 443:443
        env_file:
            - ./.env
        working_dir: /var/www/html
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ../app:/var/www/html
            - data:/etc/letsencrypt
            - data:/var/log/nginx

    db:
        image: mysql:8
        container_name: db-${PROJECT_NAME}
        ports:
            - 3306:3306
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=true
            #- MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=${PROJECT_NAME}
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=admin
        env_file:
            - ./.env
        volumes:
            - data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin-${PROJECT_NAME}
        links:
            - db
        ports:
            - 8080:80

    node:
        build:
            context: ./node
            dockerfile: ./Dockerfile
        container_name: node-${PROJECT_NAME}
        tty: true
        working_dir: /var/www
        volumes:
            - ../app:/var/www
        env_file:
            - ./.env

volumes:
    data: {}
