version: '3'

services:
    db:
        build: ./db
        container_name: db-${PROJECT_NAME}
        ports:
            - ${DATABASE_PORT}:3306
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${PROJECT_NAME}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - ./db/db-persist:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.7
        container_name: phpmyadmin-${PROJECT_NAME}
        ports:
            - ${PHPMYADMIN_PORT}:80

    portainer:
        image: portainer/portainer
        container_name: portainer-${PROJECT_NAME}
        command: -H unix:///var/run/docker.sock
        ports:
            - ${PORTAINER_PORT}:9000
        volumes:
            - data:/var/run/docker.sock
            - data:/data

    rancher:
        image: rancher/rancher
        container_name: rancher-${PROJECT_NAME}
